version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: stock_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stock_rdb
      MYSQL_USER: stock
      MYSQL_PASSWORD: stock
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - node.name=node-1
      - cluster.name=stock
      - network.host=0.0.0.0
    container_name: stock_es
    depends_on:
      - mysql
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./dict:/usr/share/elasticsearch/config/dict
      - ./elasticsearch-data:/var/lib/elastic

    command: /bin/sh -c "./bin/elasticsearch-plugin install analysis-nori; /usr/local/bin/docker-entrypoint.sh"

volumes:
  mysql-data:
  elasticsearch-data: